name: sos_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  flutter_masked_text2: ^0.9.1
  provider: ^6.0.5
  validatorless: ^1.2.3
  geolocator: ^9.0.2
  google_maps_flutter: ^2.5.0
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  mobx: ^2.2.0  
  flutter_mobx: ^2.0.6+5
  image_picker: ^1.0.0
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.9
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  url_launcher: ^6.1.12
  top_snackbar_flutter: ^3.1.0
  intl: ^0.18.1
  multi_image_picker_view: ^0.0.17
  flutter_native_splash: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^9.4.0
  animated_text_kit: ^4.2.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: '#FFFFFF'
  image: assets/images/splash.png
  android_gravity: center
  android12:
    color: '#FFFFFF'
    icon_background_color: "#FFFFFF"
    image: assets/images/splash.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon-android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/avatar.png
    - assets/images/logo.png
    - assets/images/splash.png
    - assets/images/icon.png
    - assets/images/icon-android.png
    - assets/images/milo.png
    - assets/images/milos-head.png
    - .env
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          style: normal
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
